In [2]:
from numpy import random

x = random.randint(100, size=(10, 3))

print(x)

[[60 66 71]
 [83  4 47]
 [76 58 96]
 [48 74 98]
 [98 87 24]
 [28 61 42]
 [ 7 53 51]
 [54 83 20]
 [55 44 65]
 [65 61 80]]
